print ('My name is Mark')
print ('I was hatched in Rocktober')
print ('I was born in Florida')
print ('My name is also Mark')
print ('I was also born in October')
print ('My favorite food is Massaman Curry')
